<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<OutputType>WinExe</OutputType>
		<StartupObject>Bwl.Storage.UniversalORM.TestApps.My.MyApplication</StartupObject>
		<MyType>WindowsForms</MyType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<UseWindowsForms>true</UseWindowsForms>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<OutputPath>..\debug\UniversalORM TestApps\bin\</OutputPath>
		<DocumentationFile>Bwl.Storage.UniversalORM.TestApps.xml</DocumentationFile>
		<NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DefineDebug>false</DefineDebug>
		<OutputPath>..\debug\UniversalORM TestApps\bin\</OutputPath>
		<DocumentationFile>Bwl.Storage.UniversalORM.TestApps.xml</DocumentationFile>
		<NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
	</PropertyGroup>
	<PropertyGroup>
		<RunPostBuildEvent>Always</RunPostBuildEvent>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="Bwl.Framework">
			<HintPath>..\refs\Bwl.Framework.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<Import Include="System.Drawing" />
		<Import Include="System.Windows.Forms" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="AdoDb\AdoDbTest.Designer.vb">
			<DependentUpon>AdoDbTest.vb</DependentUpon>
		</Compile>
		<Compile Update="Blob\BlobUORM.Designer.vb">
			<DependentUpon>BlobUORM.vb</DependentUpon>
		</Compile>
		<Compile Update="Files\FilesUORM_test.Designer.vb">
			<DependentUpon>FilesUORM_test.vb</DependentUpon>
		</Compile>
		<Compile Update="FireBirdBigData\BigDataTestForm.Designer.vb">
			<DependentUpon>BigDataTestForm.vb</DependentUpon>
		</Compile>
		<Compile Update="FireBird\FirebirdApplication.Designer.vb">
			<DependentUpon>FirebirdApplication.vb</DependentUpon>
		</Compile>
		<Compile Update="LocalStorage\LocalStorageTestDataForm.Designer.vb">
			<DependentUpon>LocalStorageTestDataForm.vb</DependentUpon>
		</Compile>
		<Compile Update="My Project\Application.Designer.vb">
			<AutoGen>True</AutoGen>
			<DependentUpon>Application.myapp</DependentUpon>
		</Compile>
		<Compile Update="My Project\Resources.Designer.vb">
			<AutoGen>True</AutoGen>
			<DesignTime>True</DesignTime>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<Compile Update="My Project\Settings.Designer.vb">
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<None Update="My Project\Application.myapp">
			<Generator>MyApplicationCodeGenerator</Generator>
			<LastGenOutput>Application.Designer.vb</LastGenOutput>
		</None>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Bwl.Storage.UniversalORM.Firebird\Bwl.Storage.UniversalORM.Firebird.vbproj" />
		<ProjectReference Include="..\Bwl.Storage.UniversalORM\Bwl.Storage.UniversalORM.vbproj" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="..\refs\fbe32\fbclient.dll">
			<Link>fbe32\fbclient.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\firebird.conf">
			<Link>fbe32\firebird.conf</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\icudt63.dll">
			<Link>fbe32\icudt63.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\icudt63l.dat">
			<Link>fbe32\icudt63l.dat</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\icuin63.dll">
			<Link>fbe32\icuin63.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\icuuc63.dll">
			<Link>fbe32\icuuc63.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\plugins\chacha.dll">
			<Link>fbe32\plugins\chacha.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\plugins\default_profiler.dll">
			<Link>fbe32\plugins\default_profiler.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\plugins\engine13.dll">
			<Link>fbe32\plugins\engine13.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\plugins\fbtrace.dll">
			<Link>fbe32\plugins\fbtrace.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\plugins\legacy_auth.dll">
			<Link>fbe32\plugins\legacy_auth.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\plugins\legacy_usermanager.dll">
			<Link>fbe32\plugins\legacy_usermanager.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\plugins\srp.dll">
			<Link>fbe32\plugins\srp.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\plugins\udr_engine.conf">
			<Link>fbe32\plugins\udr_engine.conf</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\plugins\udr_engine.dll">
			<Link>fbe32\plugins\udr_engine.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\plugins\udr\udf_compat.dll">
			<Link>fbe32\plugins\udr\udf_compat.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\plugins\udr\UdfBackwardCompatibility.sql">
			<Link>fbe32\plugins\udr\UdfBackwardCompatibility.sql</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe32\plugins\udr\udrcpp_example.dll">
			<Link>fbe32\plugins\udr\udrcpp_example.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\fbclient.dll">
			<Link>fbe64\fbclient.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\firebird.conf">
			<Link>fbe64\firebird.conf</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\icudt63.dll">
			<Link>fbe64\icudt63.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\icudt63l.dat">
			<Link>fbe64\icudt63l.dat</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\icuin63.dll">
			<Link>fbe64\icuin63.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\icuuc63.dll">
			<Link>fbe64\icuuc63.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\plugins\chacha.dll">
			<Link>fbe64\plugins\chacha.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\plugins\default_profiler.dll">
			<Link>fbe64\plugins\default_profiler.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\plugins\engine13.dll">
			<Link>fbe64\plugins\engine13.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\plugins\fbtrace.dll">
			<Link>fbe64\plugins\fbtrace.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\plugins\legacy_auth.dll">
			<Link>fbe64\plugins\legacy_auth.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\plugins\legacy_usermanager.dll">
			<Link>fbe64\plugins\legacy_usermanager.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\plugins\srp.dll">
			<Link>fbe64\plugins\srp.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\plugins\udr_engine.conf">
			<Link>fbe64\plugins\udr_engine.conf</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\plugins\udr_engine.dll">
			<Link>fbe64\plugins\udr_engine.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\plugins\udr\udf_compat.dll">
			<Link>fbe64\plugins\udr\udf_compat.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\plugins\udr\UdfBackwardCompatibility.sql">
			<Link>fbe64\plugins\udr\UdfBackwardCompatibility.sql</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\refs\fbe64\plugins\udr\udrcpp_example.dll">
			<Link>fbe64\plugins\udr\udrcpp_example.dll</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="FirebirdSql.Data.FirebirdClient" Version="10.3.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.Buffers" Version="4.6.0" />
		<PackageReference Include="System.Memory" Version="4.6.0" />
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.0" />
		<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.0" />
	</ItemGroup>
</Project>