<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <StartupObject>Bwl.Storage.UniversalORM.TestApps.My.MyApplication</StartupObject>
    <MyType>WindowsForms</MyType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\debug\UniversalORM TestApps\bin\</OutputPath>
    <DocumentationFile>Bwl.Storage.UniversalORM.TestApps.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DefineDebug>false</DefineDebug>
    <OutputPath>..\debug\UniversalORM TestApps\bin\</OutputPath>
    <DocumentationFile>Bwl.Storage.UniversalORM.TestApps.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
  </PropertyGroup>
  <ItemGroup>
	  <Reference Include="Bwl.Framework">
		  <HintPath>..\refs\Bwl.Framework.dll</HintPath>
	  </Reference>
    <Reference Include="FirebirdSql.Data.FirebirdClient, Version=4.5.0.0, Culture=neutral, PublicKeyToken=3750abcc3150b00c, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\refs\FirebirdSql.Data.FirebirdClient.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\refs\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="AdoDb\AdoDbTest.Designer.vb">
      <DependentUpon>AdoDbTest.vb</DependentUpon>
    </Compile>
    <Compile Update="Blob\BlobUORM.Designer.vb">
      <DependentUpon>BlobUORM.vb</DependentUpon>
    </Compile>
    <Compile Update="Files\FilesUORM_test.Designer.vb">
      <DependentUpon>FilesUORM_test.vb</DependentUpon>
    </Compile>
    <Compile Update="FireBirdBigData\BigDataTestForm.Designer.vb">
      <DependentUpon>BigDataTestForm.vb</DependentUpon>
    </Compile>
    <Compile Update="FireBird\FirebirdApplication.Designer.vb">
      <DependentUpon>FirebirdApplication.vb</DependentUpon>
    </Compile>
    <Compile Update="LocalStorage\LocalStorageTestDataForm.Designer.vb">
      <DependentUpon>LocalStorageTestDataForm.vb</DependentUpon>
    </Compile>
    <Compile Update="My Project\Application.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="My Project\Settings.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\refs\fbe32\aliases.conf">
      <Link>fbe32\aliases.conf</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\refs\fbe32\firebird.conf">
      <Link>fbe32\firebird.conf</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\refs\fbe32\firebird.msg">
      <Link>fbe32\firebird.msg</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\refs\fbe64\aliases.conf">
      <Link>fbe64\aliases.conf</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\refs\fbe64\firebird.conf">
      <Link>fbe64\firebird.conf</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\refs\fbe64\firebird.log">
      <Link>fbe64\firebird.log</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\refs\fbe64\firebird.msg">
      <Link>fbe64\firebird.msg</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bwl.Storage.UniversalORM.Firebird\Bwl.Storage.UniversalORM.Firebird.vbproj" />
    <ProjectReference Include="..\Bwl.Storage.UniversalORM\Bwl.Storage.UniversalORM.vbproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\refs\fbe32\fbembed.dll">
      <Link>fbe32\fbembed.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\refs\fbe32\ib_util.dll">
      <Link>fbe32\ib_util.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\refs\fbe32\icudt30.dll">
      <Link>fbe32\icudt30.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\refs\fbe32\icuin30.dll">
      <Link>fbe32\icuin30.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\refs\fbe32\icuuc30.dll">
      <Link>fbe32\icuuc30.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\refs\fbe32\msvcp80.dll">
      <Link>fbe32\msvcp80.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\refs\fbe32\msvcr80.dll">
      <Link>fbe32\msvcr80.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\refs\fbe64\fbembed.dll">
      <Link>fbe64\fbembed.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\refs\fbe64\ib_util.dll">
      <Link>fbe64\ib_util.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\refs\fbe64\icudt30.dll">
      <Link>fbe64\icudt30.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\refs\fbe64\icuin30.dll">
      <Link>fbe64\icuin30.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\refs\fbe64\icuuc30.dll">
      <Link>fbe64\icuuc30.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\refs\fbe64\msvcp80.dll">
      <Link>fbe64\msvcp80.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\refs\fbe64\msvcr80.dll">
      <Link>fbe64\msvcr80.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>