'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.17929
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Bwl.Storage.UniversalORM.Firebird.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на ALTER TABLE {0} ADD &quot;{1}&quot; bigint .
        '''</summary>
        Friend ReadOnly Property AddBigIntColumn() As String
            Get
                Return ResourceManager.GetString("AddBigIntColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на ALTER TABLE {0} ADD &quot;{1}&quot; float.
        '''</summary>
        Friend ReadOnly Property AddFloatColumn() As String
            Get
                Return ResourceManager.GetString("AddFloatColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на ALTER TABLE {0} ADD &quot;{1}&quot; integer.
        '''</summary>
        Friend ReadOnly Property AddIntColumn() As String
            Get
                Return ResourceManager.GetString("AddIntColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на ALTER TABLE {0} ADD &quot;{1}&quot; varchar({2})  .
        '''</summary>
        Friend ReadOnly Property AddStringColumn() As String
            Get
                Return ResourceManager.GetString("AddStringColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на CREATE TABLE {0}(
        '''	guid char(38) NOT NULL,
        '''	val bigint NOT NULL,
        ''' CONSTRAINT PK_{0} PRIMARY KEY CLUSTERED 
        '''(
        '''	guid 
        ''')
        '''CREATE INDEX IX_{0} ON {0}
        '''(
        '''	val 
        ''').
        '''</summary>
        Friend ReadOnly Property CreateBigIntIndexTableSQL() As String
            Get
                Return ResourceManager.GetString("CreateBigIntIndexTableSQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на CREATE TABLE {0}
        '''(
        '''    guid varchar(38) NOT NULL UNIQUE,
        '''    val float NOT NULL,
        '''    CONSTRAINT PK_{0} PRIMARY KEY (guid)
        ''')
        '''CREATE INDEX IX_{0} ON {0} (val ascending).
        '''</summary>
        Friend ReadOnly Property CreateFloatIndexTableSQL() As String
            Get
                Return ResourceManager.GetString("CreateFloatIndexTableSQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на CREATE ASCENDING INDEX &quot;IX_{1}&quot; ON {0}
        '''(
        '''    &quot;{1}&quot;
        ''').
        '''</summary>
        Friend ReadOnly Property CreateIndexSQL() As String
            Get
                Return ResourceManager.GetString("CreateIndexSQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на CREATE TABLE {0}
        '''(
        '''    guid varchar(38) NOT NULL,
        '''    value int NOT NULL,
        '''    CONSTRAINT PK_{0} PRIMARY KEY 
        '''    (
        '''        guid  ASC
        '''    )
        ''')
        '''CREATE INDEX IX_{0} ON {0}
        '''(
        '''    value ASC
        ''').
        '''</summary>
        Friend ReadOnly Property CreateIntIndexTableSQL() As String
            Get
                Return ResourceManager.GetString("CreateIntIndexTableSQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на CREATE TABLE {0}
        '''(
        '''    guid varchar(38) NOT NULL,
        '''    type varchar(4096) ,
        '''    json varchar(4096),                                                                                CONSTRAINT PK_{0} PRIMARY KEY
        '''(
        '''    guid
        ''')
        ''').
        '''</summary>
        Friend ReadOnly Property CreateMainTableSQL() As String
            Get
                Return ResourceManager.GetString("CreateMainTableSQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на CREATE TABLE {0}
        '''(
        '''	guid char(38) NOT NULL,
        '''	val varchar({2}) NOT NULL,
        '''	 CONSTRAINT PK_{0} PRIMARY KEY
        '''	(
        '''		guid
        '''	)
        ''').
        '''</summary>
        Friend ReadOnly Property CreateStringTableSQL() As String
            Get
                Return ResourceManager.GetString("CreateStringTableSQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на UPDATE {0} SET &quot;{1}&quot; = {3}
        '''     WHERE guid = &apos;{2}&apos;.
        '''</summary>
        Friend ReadOnly Property UpdateIndexSQL() As String
            Get
                Return ResourceManager.GetString("UpdateIndexSQL", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
