'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Bwl.Storage.UniversalORM.Sqlite.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ALTER TABLE &quot;{0}&quot; ADD &quot;{1}&quot; bigint .
        '''</summary>
        Friend ReadOnly Property AddBigIntColumn() As String
            Get
                Return ResourceManager.GetString("AddBigIntColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ALTER TABLE &quot;{0}&quot; ADD &quot;{1}&quot; boolean .
        '''</summary>
        Friend ReadOnly Property AddBoolColumn() As String
            Get
                Return ResourceManager.GetString("AddBoolColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ALTER TABLE &quot;{0}&quot; ADD &quot;{1}&quot; float.
        '''</summary>
        Friend ReadOnly Property AddFloatColumn() As String
            Get
                Return ResourceManager.GetString("AddFloatColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ALTER TABLE &quot;{0}&quot; ADD &quot;{1}&quot;integer.
        '''</summary>
        Friend ReadOnly Property AddIntColumn() As String
            Get
                Return ResourceManager.GetString("AddIntColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ALTER TABLE &quot;{0}&quot; ADD &quot;{1}&quot; varchar({2})  .
        '''</summary>
        Friend ReadOnly Property AddStringColumn() As String
            Get
                Return ResourceManager.GetString("AddStringColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE &quot;{0}&quot; 
        '''(
        '''    guid varchar(38) NOT NULL,
        '''    type varchar(5000) ,
        '''    json text,                                                                                CONSTRAINT PK_{0} PRIMARY KEY
        '''(
        '''    guid
        ''')
        ''').
        '''</summary>
        Friend ReadOnly Property CreateMainTableSQL() As String
            Get
                Return ResourceManager.GetString("CreateMainTableSQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE &quot;{0}&quot; SET &quot;{1}&quot; = {3}
        '''  WHERE guid = &apos;{2}&apos;.
        '''</summary>
        Friend ReadOnly Property UpdateIndexSQL() As String
            Get
                Return ResourceManager.GetString("UpdateIndexSQL", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
