<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<OutputType>Library</OutputType>
		<RootNamespace>CommonUnitTests</RootNamespace>
		<AssemblyName>CommonUnitTests</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<OutputPath>..\debug\UnitTests\bin\</OutputPath>
		<DocumentationFile>CommonUnitTests.xml</DocumentationFile>
		<NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DefineDebug>false</DefineDebug>
		<OutputPath>..\debug\UnitTests\</OutputPath>
		<DocumentationFile>CommonUnitTests.xml</DocumentationFile>
		<NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
	</PropertyGroup>
	<PropertyGroup>
		<RunPostBuildEvent>Always</RunPostBuildEvent>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="Bwl.Framework">
			<HintPath>..\refs\Bwl.Framework.dll</HintPath>
		</Reference>
		<Reference Include="FirebirdSql.Data.FirebirdClient">
			<HintPath>..\refs\FirebirdSql.Data.FirebirdClient.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<Compile Update="My Project\Resources.Designer.vb">
			<AutoGen>True</AutoGen>
			<DesignTime>True</DesignTime>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Update="My Project\Resources.resx">
			<Generator>VbMyResourcesResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.vb</LastGenOutput>
			<CustomToolNamespace>My.Resources</CustomToolNamespace>
			<SubType>Designer</SubType>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Bwl.Storage.UniversalORM.Firebird\Bwl.Storage.UniversalORM.Firebird.vbproj" />
		<ProjectReference Include="..\Bwl.Storage.UniversalORM.MSSQL\Bwl.Storage.UniversalORM.MSSQL.vbproj" />
		<ProjectReference Include="..\Bwl.Storage.UniversalORM.Postgresql\Bwl.Storage.UniversalORM.Postgresql.vbproj" />
		<ProjectReference Include="..\Bwl.Storage.UniversalORM.SkiaSharp\Bwl.Storage.UniversalORM.SkiaSharp.vbproj" />
		<ProjectReference Include="..\Bwl.Storage.UniversalORM.Sqlite\Bwl.Storage.UniversalORM.Sqlite.vbproj" />
		<ProjectReference Include="..\Bwl.Storage.UniversalORM\Bwl.Storage.UniversalORM.vbproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
		<PackageReference Include="NUnit" Version="4.3.2" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
	</ItemGroup>
	<PropertyGroup>
		<MyType>Empty</MyType>
	</PropertyGroup>

</Project>